[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
  '@foundry-devops/=lib/foundry-devops/',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  'ds-test/=lib/solmate/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  'solmate/=lib/solmate/src/'
]
fs_permissions = [{ access = "read", path = "./broadcast" }]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
zksync-local = "http://127.0.0.1:8011"

[invariant]
runs = 64
depth = 64
fail_on_revert = true